
version: '3'

services:
  emotions:
    build:
      context: .
      dockerfile: Dockerfile
    image: emotions-docker
    container_name: emotions-app-api
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      MONGODB: ${MONGODB}
      JWT_SECRET: ${JWT_SECRET}
