import { IMPORT_EXPORT_FEATURE, LOGGER_FEATURE, VALIDATE_PERMISSIONS_FEATURE } from '.';

export const articleFeatures = [
  IMPORT_EXPORT_FEATURE,
  LOGGER_FEATURE,
  VALIDATE_PERMISSIONS_FEATURE,
];
