
name: CI Workflow

on:
  push:
    branches: [feature/nest-transition]
  pull_request:
    branches: [master]

jobs:
  ci:
    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set Up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: yarn install

    - name: Build
      run: yarn build
    
    - name: Run Tests
      run: yarn test