
name: CD Workflow

on:
  workflow_run:
    workflows: ["CI Workflow"]
    types: [completed]

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Docker Container Deployment to Heroku
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}